"""
Database utility functions for inserting scraped data
"""
import logging
from typing import List, Dict, Optional
from config import supabase, mongodb_db
import uuid
from datetime import datetime, timedelta

logger = logging.getLogger(__name__)

def generate_id() -> str:
    """Generate a unique ID (used for tables that expect strings/UUIDs)

    Note: `COUNTRY` and `CITY` use bigint primary keys in the DB, so
    those functions should not call `generate_id()`.
    """
    return str(uuid.uuid4())

def insert_country(country_name: str) -> Optional[int]:
    """Insert or get country ID"""
    if not supabase:
        logger.error("Supabase not initialized")
        return None
    
    try:
        # Check if country exists (DB returns bigint CountryID)
        result = supabase.table('COUNTRY').select('CountryID').eq('CountryName', country_name).execute()

        if result.data and len(result.data) > 0:
            logger.info(f"Country '{country_name}' already exists")
            try:
                return int(result.data[0]['CountryID'])
            except Exception:
                return None

        # Insert new country and let Postgres generate CountryID (bigint)
        data = {
            'CountryName': country_name
        }

        result = supabase.table('COUNTRY').insert(data).execute()
        if result.data and len(result.data) > 0:
            try:
                country_id = int(result.data[0]['CountryID'])
                logger.info(f"✅ Inserted country: {country_name} (CountryID={country_id})")
                return country_id
            except Exception as e:
                logger.error(f"Inserted country but failed to parse CountryID: {e}")
                return None
        else:
            logger.error(f"Failed to insert country: {country_name} (no result data)")
            return None
    except Exception as e:
        logger.error(f"Error inserting country '{country_name}': {e}")
        return None

def insert_city(city_name: str, country_id: int) -> Optional[int]:
    """Insert or get city ID"""
    if not supabase:
        logger.error("Supabase not initialized")
        return None
    
    try:
        # Check if city exists (CityID is bigint)
        result = supabase.table('CITY').select('CityID').eq('CityName', city_name).eq('CountryID', country_id).execute()

        if result.data and len(result.data) > 0:
            logger.info(f"City '{city_name}' already exists")
            try:
                return int(result.data[0]['CityID'])
            except Exception:
                return None

        # Insert new city and let Postgres generate CityID (bigint)
        data = {
            'CountryID': country_id,
            'CityName': city_name
        }

        result = supabase.table('CITY').insert(data).execute()
        if result.data and len(result.data) > 0:
            try:
                city_id = int(result.data[0]['CityID'])
                logger.info(f"✅ Inserted city: {city_name} (CityID={city_id})")
                return city_id
            except Exception as e:
                logger.error(f"Inserted city but failed to parse CityID: {e}")
                return None
        else:
            logger.error(f"Failed to insert city: {city_name} (no result data)")
            return None
    except Exception as e:
        logger.error(f"Error inserting city '{city_name}': {e}")
        return None

def insert_hotel(hotel_data: Dict) -> Optional[int]:
    """Insert hotel and return hotel ID (bigint, auto-generated by DB)"""
    if not supabase:
        logger.error("Supabase not initialized")
        return None
    
    try:
        data = {
            'HotelName': hotel_data['name'],
            'HotelRating': int(hotel_data.get('rating', 0)),
            'CityID': hotel_data['city_id']
        }
        
        result = supabase.table('HOTEL').insert(data).execute()
        if result.data and len(result.data) > 0:
            try:
                hotel_id = int(result.data[0]['HotelID'])
                logger.info(f"✅ Inserted hotel: {hotel_data['name']} (HotelID={hotel_id})")
                
                # Insert hotel images if provided
                if 'images' in hotel_data and hotel_data['images']:
                    insert_hotel_images(hotel_id, hotel_data['images'])
                
                return hotel_id
            except Exception as e:
                logger.error(f"Inserted hotel but failed to parse HotelID: {e}")
                return None
        else:
            logger.error(f"Failed to insert hotel: {hotel_data['name']} (no result data)")
            return None
    except Exception as e:
        logger.error(f"Error inserting hotel: {e}")
        return None

def insert_hotel_images(hotel_id: int, images: List[str]):
    """Insert hotel images"""
    if not supabase:
        return
    
    try:
        image_data = [
            {'HotelID': hotel_id, 'HotelImage': img_url}
            for img_url in images
        ]
        
        result = supabase.table('HOTEL_IMAGE').insert(image_data).execute()
        logger.info(f"✅ Inserted {len(images)} images for hotel {hotel_id}")
    except Exception as e:
        logger.error(f"Error inserting hotel images: {e}")

def insert_room_type(hotel_id: int, room_data: Dict) -> Optional[int]:
    """Insert room type and return room type ID (bigint, auto-generated by DB)"""
    if not supabase:
        logger.error("Supabase not initialized")
        return None
    
    try:
        data = {
            'HotelID': hotel_id,
            'RoomTypeName': room_data['name'],
            'Price': room_data['price'],
            'Capacity': room_data.get('capacity', 2)
        }
        
        result = supabase.table('ROOM_TYPE').insert(data).execute()
        if result.data and len(result.data) > 0:
            try:
                room_type_id = int(result.data[0]['RoomTypeID'])
                logger.info(f"✅ Inserted room type: {room_data['name']} (RoomTypeID={room_type_id})")
                
                # Insert availability if provided
                if 'availability' in room_data:
                    insert_availability(room_type_id, room_data['availability'])
                
                return room_type_id
            except Exception as e:
                logger.error(f"Inserted room type but failed to parse RoomTypeID: {e}")
                return None
        else:
            logger.error(f"Failed to insert room type: {room_data['name']} (no result data)")
            return None
    except Exception as e:
        logger.error(f"Error inserting room type: {e}")
        return None

def insert_availability(room_type_id: int, availability_data: Dict):
    """Insert availability data for a room type"""
    if not supabase:
        return
    
    try:
        # Generate availability for next 90 days
        start_date = datetime.now()
        availability_records = []
        
        for i in range(90):
            date = start_date + timedelta(days=i)
            date_str = date.strftime('%Y-%m-%d')
            
            # Get number of rooms available (default or from data)
            num_rooms = availability_data.get(date_str, availability_data.get('default', 10))
            
            availability_records.append({
                'RoomTypeID': room_type_id,
                'Date': date_str,
                'NumberOfRooms': num_rooms
            })
        
        # Insert in batches
        batch_size = 30
        for i in range(0, len(availability_records), batch_size):
            batch = availability_records[i:i + batch_size]
            result = supabase.table('AVAILABILITY').insert(batch).execute()
        
        logger.info(f"✅ Inserted availability for room type {room_type_id}")
    except Exception as e:
        logger.error(f"Error inserting availability: {e}")

def insert_review(hotel_id: int, user_id: str, review_text: str, rating: float = 0):
    """Insert a review"""
    if not supabase:
        return
    
    try:
        data = {
            'HotelID': hotel_id,
            'UserID': user_id,
            'Review': review_text
        }
        
        result = supabase.table('REVIEW').insert(data).execute()
        logger.info(f"✅ Inserted review for hotel {hotel_id}")
    except Exception as e:
        logger.error(f"Error inserting review: {e}")






